spring.application.name=PE_SBA301_SP25_BE_DE190224

# ================== DATABASE ==================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CarStore2025DB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ================== SERVER ==================
server.port=8080
logging.level.org.springframework.security=DEBUG
# ================== JWT ==================
jwt.secret=YTM0NTY3ODlhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejAxMjM0NTY3ODlBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWg==
jwt.expiration=86400000   