spring.application.name=lab8
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Phai co chu .data. o giua
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=SBA301DB
server.port=8080
